dist: xenial
addons:
  snaps:
  - name: dotnet-sdk
    classic: true
    channel: 5.0/beta
sudo: required
language: csharp
mono: none
script:
  - sudo snap alias dotnet-sdk.dotnet dotnet
  - dotnet restore src
  - dotnet build src -c Release --no-restore